### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by afgtube** [DanielnetoDotCom/YouPHPTube#1000]
can someone helpe me how to fix it.
The page does not work

afgtube.kamiaq.com can not process this request at this time.
HTTP ERROR 500

**Comment by DanielnetoDotCom** [comment]
check your log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by afgtube** [comment]
hello how to fix this:

[24-Aug-2018 16:11:11 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php:8
Stack trace:
#0 /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php(8): DateTime->__construct()
#1 /home/kamiaqco/Afgtube.kamiaq.com/videos/configuration.php(19): require_once('/home/kamiaqco/...')
#2 /home/kamiaqco/Afgtube.kamiaq.com/install/index.php(23): require_once('/home/kamiaqco/...')
#3 {main}
  thrown in /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php on line 8
[24-Aug-2018 16:11:40 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php:8
Stack trace:
#0 /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php(8): DateTime->__construct()
#1 /home/kamiaqco/Afgtube.kamiaq.com/videos/configuration.php(19): require_once('/home/kamiaqco/...')
#2 /home/kamiaqco/Afgtube.kamiaq.com/index.php(126): require_once('/home/kamiaqco/...')
#3 {main}
  thrown in /home/kamiaqco/Afgtube.kamiaq.com/objects/include_config.php on line 8

**Comment by DanielnetoDotCom** [comment]
First thing, google for the fatal error 

https://www.google.com.br/search?q=PHP+Fatal+error%3A+Uncaught+exception+%27Exception%27+with+message+%27DateTime%3A%3A__construct()%3A+It+is+not+safe+to+rely+on+the+system%27s+timezone+settings.&oq=PHP+Fatal+error%3A+Uncaught+exception+%27Exception%27+with+message+%27DateTime%3A%3A__construct()%3A+It+is+not+safe+to+rely+on+the+system%27s+timezone+settings.&aqs=chrome..69i57j69i64.343j0j7&sourceid=chrome&ie=UTF-8
