### ISSUE TITLE
Send webhook notification

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1196]
I would like to add this code to trigger on video upload to send a notification in discord using webhooks: 
```<?php
function postToDiscord($title, $videoThumbnail, $uploaderName, $uploaderChannel, $videoTitle, $videoDescription, $videoLink) {
	$url = "https://ptb.discordapp.com/api/webhooks/xxxxxxx/xxxxxxx";
	$mess = json_encode([
    "username" => "PuyoTube Bot",
    "avatar_url" => "",
    "tts" => false,
    "embeds" => [
        [
            "title" => $title,
            "type" => "rich",
            "description" => "",
            "color" => hexdec( "FF0000" ),
            "footer" => [
                "text" => "PuyoTube",
                "icon_url" => "https://puyodead1-development.me/videos/userPhoto/logo.png"
            ],
            "image" => [
                "url" => $videoThumbnail
            ],
            "fields" => [
                [
                    "name" => "User",
                    "value" => $uploaderName,
                    "inline" => true
                ],
                [
                    "name" => "User Channel",
                    "value" => $uploaderChannel,
                    "inline" => true
                ],
                [
                    "name" => "Video Title",
                    "value" => $videoTitle,
                    "inline" => true
                ],
				[
                    "name" => "Video Description",
                    "value" => $videoDescription,
                    "inline" => true
                ],
				[
                    "name" => "Video Link",
                    "value" => $videoLink,
                    "inline" => true
                ]
            ]
        ]
    ]

], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
    $ch = curl_init();

curl_setopt_array( $ch, [
    CURLOPT_URL => $url,
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => $mess,
    CURLOPT_HTTPHEADER => [
        "Length" => strlen( $mess ),
        "Content-Type" => "application/json"
    ]
]);

$response = curl_exec( $ch );
curl_close( $ch );
}

then post the info
postToDiscord();
?>```

**Comment by DanielnetoDotCom** [comment]
Create a new plugin an overwrite this method to trigger every new video
https://github.com/DanielnetoDotCom/YouPHPTube/blob/f3428b65721e611d0d9e518642c6663f38c08dae/plugin/Plugin.abstract.php#L154

**Comment by Puyodead1** [comment]
<3 thanks

**Comment by DanielnetoDotCom** [comment]
You should add a method to overwrite the parent one, probably:

```
public function afterNewVideo($videos_id) {
        return $this->sendNotification($videos_id);
}
```

**Comment by Puyodead1** [comment]
```[31-Oct-2018 07:44:27 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function sendNotification() in /var/www/html/tube/plugin/DiscordNotify/DiscordNotify.php:40
Stack trace:
#0 /var/www/html/tube/plugin/YouPHPTubePlugin.php(371): DiscordNotify->afterNewVideo(20)
#1 /var/www/html/tube/objects/youPHPTubeEncoderNotifyIsDone.json.php(58): YouPHPTubePlugin::afterNewVideo(20)
#2 {main}
  thrown in /var/www/html/tube/plugin/DiscordNotify/DiscordNotify.php on line 40
[31-Oct-2018 07:46:26 America/New_York] PHP Fatal error:  Uncaught Error: Class 'DiscordNotify' not found in /var/www/html/tube/plugin/YouPHPTubePlugin.php(229) : eval()'d code:1
Stack trace:
#0 /var/www/html/tube/plugin/YouPHPTubePlugin.php(229): eval()
#1 /var/www/html/tube/plugin/YouPHPTubePlugin.php(349): YouPHPTubePlugin::loadPlugin('DiscordNotify')
#2 /var/www/html/tube/objects/include_config.php(52): YouPHPTubePlugin::getStart()
#3 /videos/configuration.php(19): require_once('/var/www/html/t...')
#4 /var/www/html/tube/view/managerVideos.php(4): require_once('/videos/configu...')
#5 {main}
  thrown in /var/www/html/tube/plugin/YouPHPTubePlugin.php(229) : eval()'d code on line 1```

**Comment by DanielnetoDotCom** [comment]
`PHP Fatal error:  Uncaught Error: Class 'DiscordNotify' not found in /var/www/html/tube/plugin/YouPHPTubePlugin.php(229) : eval()'d code:1`


Make sure you change the getUUID, each plugin must have a different UUID

```
public function getUUID() {
        return "cf145581-7d5e-4bb6-8c12-48fc37c0630c";
}
```

you have used the same as the LiveUsers plugin

**Comment by Puyodead1** [comment]
oops, :P thanks

**Comment by DanielnetoDotCom** [comment]
Is that working?

**Comment by Puyodead1** [comment]
seems to be

**Comment by Puyodead1** [comment]
cant get video description tho

**Comment by DanielnetoDotCom** [comment]
Sorry what do you mean?

**Comment by Puyodead1** [comment]
when i try to get the video description, it stops working and doesnt send

**Comment by Puyodead1** [comment]
same thing with duration

**Comment by Puyodead1** [comment]
```
<?php

global $global;
require_once $global['systemRootPath'] . 'plugin/Plugin.abstract.php';

class DiscordNotify extends PluginAbstract {

    public function getDescription() {
        return "Send video upload notifications to discord webhook";
    }

    public function getName() {
        return "DiscordNotify";
    }

    public function getUUID() {
        return "cf145581-7d5e-4bb6-8c12-48fc37c0630c";
    }
	public function getTags() {
		return array('free', 'notify', 'webhook');
	}
	public function sendNotification($videos_id) {
		$users_id = Video::getOwner($videos_id);
		$user = new User($users_id);
		$username = $user->getNameIdentification();
		$userChannel = $user->getChannelName();
		$userThumbnail = $user->getphotoURL();
		$video = new Video("","",$videos_id);
		$videoLink = Video::getPermaLink($videos_id);
		$videoDescription = Video::getDescription($videos_id);
		$videoDuration = Video::getDuration($videos_id);
		$url = "discord webhok";
		$mess = json_encode([
    "username" => "PuyoTube Bot",
    "avatar_url" => "",
    "tts" => false,
    "embeds" => [
        [
            "title" => $username . " just uploaded a video",
            "type" => "rich",
            "description" => "",
            "color" => hexdec( "FF0000" ),
            "footer" => [
                "text" => "PuyoTube",
                "icon_url" => "https://puyodead1-development.me/videos/userPhoto/logo.png"
            ],
            "image" => [
                "url" => $videoThumbnail
            ],
			"thumbnail" => [
				"url" => $userThumbnail
			],
            "fields" => [
                [
                    "name" => "User",
                    "value" => $username,
                    "inline" => true
                ],
                [
                    "name" => "User Channel",
                    "value" => "https://puyodead1-development.me/channel/". $userChannel,
                    "inline" => true
                ],
                [
                    "name" => "Video Title",
                    "value" => $video,
                    "inline" => true
                ],
				[
                    "name" => "Video Description",
                    "value" => $videoDescription,
                    "inline" => true
                ],
				[
                    "name" => "Video Link",
                    "value" => $videoLink,
                    "inline" => true
                ],
				[
                    "name" => "Video Duration",
                    "value" => $videoDuration,
                    "inline" => true
                ]
            ]
        ]
    ]

], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
    $ch = curl_init();

curl_setopt_array( $ch, [
    CURLOPT_URL => $url,
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => $mess,
    CURLOPT_HTTPHEADER => [
        "Length" => strlen( $mess ),
        "Content-Type" => "application/json"
    ]
]);

$response = curl_exec( $ch );
curl_close( $ch );
	}
	public function afterNewVideo($videos_id) {
        return $this->sendNotification($videos_id);
    }
}
```

**Comment by DanielnetoDotCom** [comment]
I cant see in your code where are you trying to get description and duration

if is there 

```
[
                    "name" => "Video Duration",
                    "value" => $videoDuration,
                    "inline" => true
                ]
```

you probably are not treating the json types properly

I can't teach you that but you should use quotes 

```
[
                    "name" => "Video Duration",
                    "value" => "$videoDuration",
                    "inline" => true
                ]
```

**Comment by Puyodead1** [comment]
Okay, i just checked again and duration is working now. will try working on description

**Comment by Puyodead1** [comment]
```
public function sendNotification($videos_id) {
		$users_id = Video::getOwner($videos_id);
		$user = new User($users_id);
		$username = $user->getNameIdentification();
		$userChannel = $user->getChannelName();
		$userThumbnail = $user->getphotoURL();
		$video = new Video("","",$videos_id);
		$videoLink = Video::getPermaLink($videos_id);
		$videoDescription = Video::getDescription($videos_id);
		$videoDuration = Video::getDuration($videos_id);
		$url = "discord webhok";
		$mess = json_encode([
    "username" => "PuyoTube Bot",
```

**Comment by DanielnetoDotCom** [comment]
Probably description is the same quote problem, maybe inside description string, you will need to escape them

**Comment by Puyodead1** [comment]
ok

**Comment by Puyodead1** [comment]
it says it notified in the log, but it didnt send the message

**Comment by DanielnetoDotCom** [comment]
try to debug and use some error_log() functions in your code, to try to find out what is wrong.

**Comment by Puyodead1** [comment]
okay
