### ISSUE TITLE
route not found error

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1232]
```
[19-Nov-2018 11:15:07 America/New_York] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/videos/fonts/glyphicons-halflings-regular.woff/" in /var/www/html/YouPHPTube/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/YouPHPTube/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/YouPHPTube/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/YouPHPTube/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
```

**Comment by DanielnetoDotCom** [comment]
make sure you also copy the .htaccess file and you have your mod_rewrite enabled
