### ISSUE TITLE
Can't upload movies

### ISSUE THREAD

**Issue by shortymc** [DanielnetoDotCom/YouPHPTube#1298]
Hello DanielnetoDotCom and the youphptube community !
I've just installed youphptube and the encoder on new stretch server
streamer : http://www.tradezone.tv
encoder : http://www.tradezone.tv/upload
But i can't upload movies.
mysqlnd mysql for php5 and php7
CLI is activated in php.ini 
and i made the www-data chown in 755
i can't access to the videos folder and directly in my browser like my last year install,
i don't know why. Is it a CHMOD problem ?
For testing i've also installed youtube-dl : pip install youtube-dl and i got the same problem

please help me !!

Encoder logs :
First log error : 
16-Dec-2018 10:41:52 UTC] http://www.tradezone.tv/ == http://www.tradezone.tv/
[16-Dec-2018 10:41:52 UTC] http://www.tradezone.tv/ == http://www.tradezone.tv/
[16-Dec-2018 10:41:52 UTC] Verification Start http://www.tradezone.tv/
[16-Dec-2018 10:41:52 UTC] Verification Creating the Cache http://www.tradezone.tv/
[16-Dec-2018 10:41:57 UTC] Verification Response (https://search.youphptube.com/verify.php?url=http%3A%2F%2Fwww.tradezone.tv%2F): {"msg":["Start","http:\/\/www.tradezone.tv\/ Site verified"],"verified":true,"status":"a"}
[16-Dec-2018 12:23:41 UTC] http://www.tradezone.tv/ == http://www.tradezone.tv/
[16-Dec-2018 12:23:41 UTC] http://www.tradezone.tv/ == http://www.tradezone.tv/
[16-Dec-2018 12:23:41 UTC] Verification Start http://www.tradezone.tv/
[16-Dec-2018 12:23:41 UTC] Verification Creating the Cache http://www.tradezone.tv/
[16-Dec-2018 12:23:44 UTC] Verification Response (https://search.youphptube.com/verify.php?url=http%3A%2F%2Fwww.tradezone.tv%2F): {"msg":["Start","http:\/\/www.tradezone.tv\/ Site verified"],"verified":true,"status":"a"}
[16-Dec-2018 12:26:28 UTC] MP4 All
[16-Dec-2018 12:26:28 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[16-Dec-2018 12:26:28 UTC] YouPHPTube-Encoder sending file to http://www.tradezone.tv/youPHPTubeEncoder.json
[16-Dec-2018 12:26:28 UTC] YouPHPTube-Encoder reading file from 
[16-Dec-2018 12:26:28 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":1}
[16-Dec-2018 12:26:28 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"http:\/\/www.tradezone.tv\/youPHPTubeEncoder.json","postFields":10,"response_raw":"{\"error\":false,\"video_id\":1}","response":{"error":false,"video_id":1}}
[16-Dec-2018 12:26:30 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[16-Dec-2018 12:26:35 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[16-Dec-2018 12:26:40 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[16-Dec-2018 12:26:45 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8

-----------------------------------------------------------------

this my last log errors :

018 01:57:29 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[17-Dec-2018 01:57:34 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[17-Dec-2018 01:57:39 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tv/upload/objects/include_config.php:8
Stack trace:
#0 /var/www/html/tv/upload/videos/configuration.php(18): require_once()
#1 /var/www/html/tv/upload/view/run.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tv/upload/objects/include_config.php on line 8
[17-Dec-2018 01:57:44 UTC] Getting Video File http://www.tradezone.tv/upload/videos/original_toyplaneliftoff_YPTuniqid_5c164474993723.90365404
[17-Dec-2018 01:57:44 UTC] PHP Warning:  file_put_contents(/var/www/html/tv/upload/videos/1_tmpFile.mp4): failed to open stream: Permission denied in /var/www/html/tv/upload/objects/Encoder.php on line 235
[17-Dec-2018 01:57:45 UTC] Getting from Youtube DL /usr/local/bin/youtube-dl  --force-ipv4 --no-check-certificate --no-playlist -k -o /tmp/youtubeDlTGbrJ6.mp4 -f 'mp4' "https://www.youtube.com/watch?v=CTFtOOh47oo"
[17-Dec-2018 01:57:45 UTC] /usr/local/bin/youtube-dl  --force-ipv4 --no-check-certificate --no-playlist -k -o /tmp/youtubeDlTGbrJ6.mp4 -f 'mp4' "https://www.youtube.com/watch?v=CTFtOOh47oo"
Array
(
)

[17-Dec-2018 01:58:47 UTC] Verification Start http://www.tradezone.tv/
[17-Dec-2018 01:58:47 UTC] Verification Creating the Cache http://www.tradezone.tv/
[17-Dec-2018 01:58:49 UTC] Verification Response (https://search.youphptube.com/verify.php?url=http%3A%2F%2Fwww.tradezone.tv%2F): {"msg":["Start","http:\/\/www.tradezone.tv\/ Site verified"],"verified":true,"status":"a"}
[17-Dec-2018 02:00:32 UTC] Verification Start http://www.tradezone.tv/
[17-Dec-2018 02:00:32 UTC] Verification Creating the Cache http://www.tradezone.tv/
[17-Dec-2018 02:00:34 UTC] Verification Response (https://search.youphptube.com/verify.php?url=http%3A%2F%2Fwww.tradezone.tv%2F): {"msg":["Start","http:\/\/www.tradezone.tv\/ Site verified"],"verified":true,"status":"a"}
------------------------------------------------
ps : i also see Facebook connect apps only accept https (ssl)
it was working last year but not now. Do you know a way to make apps works with http ?

 Thanks for your great job.
Best regards

**Comment by DanielnetoDotCom** [comment]
I found this "PHP Fatal error: Uncaught Error: Class 'mysqli' not found"

try to google and fix this error

**Comment by Puyodead1** [comment]
use code blocks next time also :)

**Comment by shortymc** [comment]
I try many exemple on Google.
But it's not working better
On requirements it's written php 5.6
The server run libapache2-mod-php5 with php 5.6 
phpinfo :
http://www.tradezone.tv/upload/phpinfo.php --mysqli is on

Last year i installed on stretch and it was working like this.
Maybe i need to find an older version of the encoder ?

 Thanks for your support

**Comment by shortymc** [comment]
ok, finally upload is working,
but now i can't modify parameters in admin
I don't find a full solution in Google so i explain :
i modified my php.ini file like this :
uncomment the line extension folder and put /usr/lib/php/20131226
add extension=mysqli.so 
and made php5enmodmysqli in shell
restart apache and it's done.
after i also change videos folder of site and encoder to chmod 777 (is it a good idea or it's a risk)
and it's works.

But now i can't change parameters in streamer admin area. I don't know why.
website say : a red cross and Désolé !
Tes configurations n'ont PAS été mises à jour ! in english it's something like : sorry, your configuration is not saved
I don't know why it was working yesterday.

 Can you help me please ?
Thanks for your support.
Best regards

**Comment by DanielnetoDotCom** [comment]
hi, probably is a videos directory permission.

change the videos directory (also all files into it) owner for www-data or give chamod 777

**Comment by Puyodead1** [comment]
![image](https://user-images.githubusercontent.com/14828766/50155614-8a4c8300-029a-11e9-8b50-8a0f2703ffe9.png)
PHP7 is a requirement

**Comment by shortymc** [comment]
Thanks for help 
I try It's not working :(

I also chown with another user but www-data is an authorised owner.
i made chown www-data:www-data /var/www/html/tv/videos
i try chmod 644, 666 and 777 on configuration.php
but i got the same problem.

Puyodead php7 is installed on the machine but 5.6 is activated.
Puyodead, it was working before today, yesterday i've modify site settings and all the website works, take a tour on http://www.tradezone.tv i can upload and watch movies. Last year i run it like this and it was working well.

 Thanks for your support.
Best regards

**Comment by shortymc** [comment]
...  All works but General Settings and Site settings not working, all other admin functions like categories works fine. I really don't know why only settings functions are not working. 
Please help me.
thanks for your support.
best regards

**Comment by DanielnetoDotCom** [comment]
I guess you need to install SSL to use Facebook login, it is mandatory.
