### ISSUE TITLE
Encoder stuck in an encoding loop

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1340]
I just upgraded the streamer site from version 6.2 to version 6.4. After the upgrade to version 6.4, I went and tested the upload function on the encoder.  I uploaded a test file on the encoder.  It uploaded and then the encoder said that the file was on queue.  I did this in a browser on my computer.  Using Google Chrome.  Once the file is on the encoder, I am getting an encoding loop where the uploaded file stays on the encoder, the green status bar keeps reaching 100%.  Disappears for a second, then starts over and keeps trying to encode the file over and over again and it never gets sent to the streamer.  It is like it is stuck in an encoding loop.

Here is my encoder youphptube.log

29-Dec-2018 19:33:05 UTC] MP4 All
[29-Dec-2018 19:33:05 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[29-Dec-2018 19:33:05 UTC] YouPHPTube-Encoder sending file to https://www.videorefuge.com/youPHPTubeEncoder.json
[29-Dec-2018 19:33:05 UTC] YouPHPTube-Encoder reading file from 
[29-Dec-2018 19:33:05 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":119}
[29-Dec-2018 19:33:05 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"https:\/\/www.videorefuge.com\/youPHPTubeEncoder.json","postFields":10,"response_raw":"{\"error\":false,\"video_id\":119}","response":{"error":false,"video_id":119}}
[29-Dec-2018 19:33:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/html/encoder/objects/Encoder.php:333
Stack trace:
#0 /var/www/html/encoder/objects/Encoder.php(241): Encoder::getVideoFile('https://www.vid...', '5', '/var/www/html/e...', '/var/www/html/e...')
#1 /var/www/html/encoder/objects/Encoder.php(463): Encoder::downloadFile('5')
#2 /var/www/html/encoder/view/run.php(6): Encoder::run()
#3 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 333

I even tried uploading a different file.  I get the same encoding loop.
Here is a fresh youphptube.log from my encoder for the second file upload.

[29-Dec-2018 19:39:37 UTC] MP4 All
[29-Dec-2018 19:39:37 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[29-Dec-2018 19:39:37 UTC] YouPHPTube-Encoder sending file to https://www.videorefuge.com/youPHPTubeEncoder.json
[29-Dec-2018 19:39:37 UTC] YouPHPTube-Encoder reading file from 
[29-Dec-2018 19:39:37 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":120}
[29-Dec-2018 19:39:37 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"https:\/\/www.videorefuge.com\/youPHPTubeEncoder.json","postFields":10,"response_raw":"{\"error\":false,\"video_id\":120}","response":{"error":false,"video_id":120}}
[29-Dec-2018 19:39:41 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/html/encoder/objects/Encoder.php:333
Stack trace:
#0 /var/www/html/encoder/objects/Encoder.php(241): Encoder::getVideoFile('https://www.vid...', '6', '/var/www/html/e...', '/var/www/html/e...')
#1 /var/www/html/encoder/objects/Encoder.php(463): Encoder::downloadFile('6')
#2 /var/www/html/encoder/view/run.php(6): Encoder::run()
#3 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 333

**Comment by KenRHill** [comment]
Can you please provide me with the correct procedure to update the encoder?

**Comment by DanielnetoDotCom** [comment]
You should be able to find a solution for the fatal error if you google for it.

**Comment by JaredHeath1** [comment]
Hey Daniel,

I am getting this same thing happening. I uploaded at 1.9GB file, encoding into HD and Low quality. It's not giving me a PHP error or anything. In the log there are two files uploaded. The first file didn't work, went into the loop as described above. The second file did work. They were very similar files, similar size, etc. What do you think? How can I fix this, or where should I look?

Here is my log from the encoder.
[YouPHPTube_EncodingIssue_1.txt](https://github.com/YouPHPTube/YouPHPTube/files/3124041/YouPHPTube_EncodingIssue_1.txt)
