### ISSUE TITLE
Cannot upload video 

### ISSUE THREAD

**Issue by bankpakorn** [DanielnetoDotCom/YouPHPTube#47]
Hi,Daniel 
I am Bank Pansamret @https://disqus.com/by/bankpansamret/
As my question in disqus.com that "I have question. I installed to my localhost and try upload my video. then , cannot open. I have some think troubled with developed ?" I get log file as below 
.........................................................
[27-Jun-2017 07:48:16 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 07:48:23 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 07:48:25 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 07:48:30 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 07:48:38 Asia/Bangkok] Duration founded: 0:01:00
[27-Jun-2017 07:48:38 Asia/Bangkok] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7
Stack trace:
#0 /var/www/html/tubemaster/videos/configuration.php(17): require_once()
#1 /var/www/html/tubemaster/view/mini-upload-form/videoEncoder.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tubemaster/objects/include_config.php on line 7
[27-Jun-2017 08:05:56 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:06:03 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:23 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:30 Asia/Bangkok] Duration founded: 0:00:46
[27-Jun-2017 08:08:30 Asia/Bangkok] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7
Stack trace:
#0 /var/www/html/tubemaster/videos/configuration.php(17): require_once()
#1 /var/www/html/tubemaster/view/mini-upload-form/videoEncoder.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tubemaster/objects/include_config.php on line 7
[27-Jun-2017 08:08:37 Asia/Bangkok] Duration founded: 0:10:53
[27-Jun-2017 08:08:37 Asia/Bangkok] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7
Stack trace:
#0 /var/www/html/tubemaster/videos/configuration.php(17): require_once()
#1 /var/www/html/tubemaster/view/mini-upload-form/videoEncoder.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tubemaster/objects/include_config.php on line 7
[27-Jun-2017 08:08:42 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:43 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:45 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:46 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 08:08:47 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132

**Comment by DanielnetoDotCom** [comment]
Hi can you please upload 1 video and get the log output now?
In this log I could not see anything related to video encode


Em 26 de jun de 2017 22:18, "bankpakorn" <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
I was looking this line in your log:
`PHP Fatal error: Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7`
It is probably error in php shell scrip side
Take a look on this:
https://stackoverflow.com/questions/11585399/command-line-php-mysqli-fails-but-works-via-web-server-and-works-in-local

**Comment by DanielnetoDotCom** [comment]
Looks like your Mysqli is not enabled on PHP cli mode

**Comment by bankpakorn** [comment]
I was signed in to myhost. then , upload video and get log.
...................................
[27-Jun-2017 09:39:14 Asia/Bangkok] PHP Notice:  Undefined variable: img in /var/www/html/tubemaster/view/modeYoutube.php on line 132
[27-Jun-2017 09:39:26 Asia/Bangkok] Duration founded: 0:01:00
[27-Jun-2017 09:39:26 Asia/Bangkok] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7
Stack trace:
#0 /var/www/html/tubemaster/videos/configuration.php(17): require_once()
#1 /var/www/html/tubemaster/view/mini-upload-form/videoEncoder.php(3): require_once('/var/www/html/t...')
#2 {main}
  thrown in /var/www/html/tubemaster/objects/include_config.php on line 7

**Comment by bankpakorn** [comment]
> I was looking this line in your log:
PHP Fatal error: Uncaught Error: Class 'mysqli' not found in /var/www/html/tubemaster/objects/include_config.php:7
It is probably error in php shell scrip side
Take a look on this:
https://stackoverflow.com/questions/11585399/command-line-php-mysqli-fails-but-works-via-web-server-and-works-in-local<

I checked on phpinfo 
mysqli extension 's enabled.

**Comment by DanielnetoDotCom** [comment]
is is enable for web browser/ apache, but is not enable for PHP CLI

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
