### ISSUE TITLE
captcha not loading image

### ISSUE THREAD

**Issue by amishultimatehacker** [DanielnetoDotCom/YouPHPTube#656]
captcha is suddenly not loading the image

![blivu user - google chrome](https://user-images.githubusercontent.com/20637510/39690105-8773dcaa-51f6-11e8-9d23-2890d57725a0.jpg)

Error log :

[07-May-2018 09:27:52 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:27:55 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:27:56 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:27:58 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:28:07 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:28:10 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23
[07-May-2018 09:30:57 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/blivu.com/public_html/objects/captcha.php:23
Stack trace:
#0 /var/www/blivu.com/public_html/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/blivu.com/public_html/objects/captcha.php on line 23

**Comment by amishultimatehacker** [comment]
I solved the issue, found that gd library wasn't installed
