### ISSUE TITLE
Live problem

### ISSUE THREAD

**Issue by saulo3k** [DanielnetoDotCom/YouPHPTube#801]
i'm follow this tutorial https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server
but this error when open live
![image](https://user-images.githubusercontent.com/11451595/41947343-64e6bdb0-798d-11e8-9b9d-c28c9f752e3f.png)

![image](https://user-images.githubusercontent.com/11451595/41947350-708b15da-798d-11e8-92d8-85393bfa8cc6.png)
Would you help me?

**Comment by hersche** [comment]
there is a 500 (Internal Server Error) - that can be interessting.

can you paste your videos/youphptube.log-file?

**Comment by mikweb2017** [comment]
you mix https with Http why?

look at the address of the player

**Comment by saulo3k** [comment]
i'm fix the mix, it's only http
The log after save stream:
`[27-Jun-2018 11:58:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100
[27-Jun-2018 11:58:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100
[27-Jun-2018 11:58:56 UTC] Start Login Request
[27-Jun-2018 11:58:56 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100
[27-Jun-2018 11:59:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100
[27-Jun-2018 11:59:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100
[27-Jun-2018 12:01:54 UTC] Array
(
    [scheme] => rtmp
    [host] => webnarius.com.br
    [path] => /live
    [query] => p=ff3a180b88991d2119a55a04a9cd6beb
)

[27-Jun-2018 12:01:54 UTC] Array
(
    [p] => ff3a180b88991d2119a55a04a9cd6beb
)

[27-Jun-2018 12:02:07 UTC] Array
(
    [0] => Array
        (
            [file] => /var/www/html/objects/mysql_dal.php
            [line] => 53
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::writeSql]  eval_mysql_bind failed: values and params in stmt don't match <br>
DELETE FROM live_transmitions_has_users_groups WHERE live_transmitions_id = 1 with formats i
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/plugin/Live/Objects/LiveTransmition.php
            [line] => 177
            [function] => writeSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => DELETE FROM live_transmitions_has_users_groups WHERE live_transmitions_id = 1
                    [1] => i
                    [2] => Array
                        (
                            [0] => 1
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/html/plugin/Live/saveLive.php
            [line] => 22
            [function] => deleteGroupsTrasmition
            [class] => LiveTransmition
            [object] => LiveTransmition Object
                (
                    [id:protected] => 1
                    [title:protected] => Transmissão
                    [public:protected] => 1
                    [saveTransmition:protected] => 0
                    [users_id:protected] => 1
                    [categories_id:protected] => 1
                    [key:protected] => 5b32f1f337662
                    [description:protected] => 123
                    [fieldsName:protected] => Array
                        (
                        )

                    [created] => 2018-06-26 23:53:41
                    [modified] => 2018-06-27 12:02:07
                )

            [type] => ->
            [args] => Array
                (
                )

        )

)

[27-Jun-2018 12:02:07 UTC] [sqlDAL::writeSql]  eval_mysql_bind failed: values and params in stmt don't match <br>
DELETE FROM live_transmitions_has_users_groups WHERE live_transmitions_id = 1 with formats i


i'm suspect of my local router internet not open rtmp port

in my server nmap 
Host is up (0.0000080s latency).
Not shown: 995 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
1935/tcp open  rtmp
8080/tcp open  http-proxy
8888/tcp open  sun-answerbook

in my computer executing with OBS


Host is up (0.00021s latency).
Not shown: 994 closed ports
PORT     STATE SERVICE
80/tcp   open  http
631/tcp  open  ipp
3306/tcp open  mysql
5432/tcp open  postgresql
8009/tcp open  ajp13
8080/tcp open  http-proxy

OBS RUN 
![image](https://user-images.githubusercontent.com/11451595/41972864-9844c92a-79e9-11e8-9355-1c079ab5d8fe.png)
![image](https://user-images.githubusercontent.com/11451595/41972880-a10dd2ea-79e9-11e8-93e5-7b685b6b04b4.png)


 `

**Comment by saulo3k** [comment]
When try acess this adress
http://webnarius.com.br/plugin/Live/stats.json.php?Menu
return 500 
on the log:
```
[27-Jun-2018 12:14:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:100
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(95): Live->get_data('http://webnariu...')
#1 /var/www/html/plugin/Live/stats.json.php(26): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 100

```

**Comment by hersche** [comment]
> Fatal error:  Uncaught Error: Call to undefined function curl_init()

please try to install php-curl (not 100% shure about the name, cant check atm)

    apt install php-curl

(if not found, search with "**apt search php curl**")
if it is that, i will add it to the doc.

**Comment by saulo3k** [comment]
i'm install and not work

If am i try open this adress http://webnarius.com.br:1935/live/5b32f1f337662/index.m3u8 in VLC was it work?

**Comment by saulo3k** [comment]
When access the live

**Comment by saulo3k** [comment]
my .httpaccess
<ifModule mod_headers.c>
    Header set Access-Control-Allow-Origin: *

**Comment by DanielnetoDotCom** [comment]
You can not use a Google meeting link as a livelink , live link is restricted to HLS M3u8 links

**Comment by saulo3k** [comment]
i'm not use live link =[ 
i'm disabled this plugin now

**Comment by saulo3k** [comment]
the only error now

**Comment by hersche** [comment]
i found a bug and fixed it, right now, please do a update of your youphptube-installation.

it's about this log-entry:

    [27-Jun-2018 12:02:07 UTC] [sqlDAL::writeSql]  eval_mysql_bind failed: values and params in stmt don't match <br>
    DELETE FROM live_transmitions_has_users_groups WHERE live_transmitions_id = 1 with formats i

**Comment by DanielnetoDotCom** [comment]
I said about Google meeting because the screeen you have shared 
![image](https://user-images.githubusercontent.com/18009293/41985957-1a124c86-7a0b-11e8-9d65-5940e4bee2d7.png)

**Comment by saulo3k** [comment]
Thanks Hersche

not more show
```
[27-Jun-2018 16:05:48 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:05:48 UTC] PHP Warning:  simplexml_load_string(): Active connections: 2  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:05:48 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:05:51 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:05:51 UTC] PHP Warning:  simplexml_load_string(): Active connections: 2  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:05:51 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): Active connections: 4  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): Active connections: 4  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:02 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:12 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:12 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:12 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:18 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:18 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:18 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:23 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:23 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:23 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:34 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:45 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:45 UTC] PHP Warning:  simplexml_load_string(): Active connections: 3  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:45 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:51 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:51 UTC] PHP Warning:  simplexml_load_string(): Active connections: 2  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:51 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:55 UTC] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:55 UTC] PHP Warning:  simplexml_load_string(): Active connections: 2  in /var/www/html/plugin/Live/Live.php on line 95
[27-Jun-2018 16:06:55 UTC] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/plugin/Live/Live.php on line 95
```

**Comment by saulo3k** [comment]
Only error now, after disabled live links is:

![image](https://user-images.githubusercontent.com/11451595/41986016-4c5877ec-7a0b-11e8-869c-fa156909b640.png)

**Comment by hersche** [comment]
looks like this old friend: https://github.com/DanielnetoDotCom/YouPHPTube/issues/338

not shure in this discussion, if it's getting solved there.

**Comment by DanielnetoDotCom** [comment]
@saulo3k what is your Nginx stats URL?

**Comment by saulo3k** [comment]
http://webnarius.com.br:8080/stats

**Comment by DanielnetoDotCom** [comment]
can we have your admin user and pass?

**Comment by DanielnetoDotCom** [comment]
BTW, you have configured your port to http://webnarius.com.br**:444**/live/5b34d84b65506/index.m3u8

and it should be http://webnarius.com.br:8080/live/5b34d84b65506/index.m3u8

**Comment by saulo3k** [comment]
admin
123456

**Comment by DanielnetoDotCom** [comment]
Ok, your live is now working here http://webnarius.com.br/plugin/Live/?c=5b32cf699fb8e
It was the port as I told you above

but the notification button you will need to look into your streamer log file

**Comment by saulo3k** [comment]
It worked

I am very happy

thank you so much
